### ISSUE TITLE
Erstellung von Designvorschlägen

### ISSUE THREAD

**Issue by MrHaython** [MrHaython/english#3]
Bevor wir anfangen können sollten wir einige Designvorschläge erstellen. Am besten erstellt jeder ein oder zwei Designideen (ob als PSD, ILLU oder HTML), damit wir diese ausdiskutieren können und einige Ideen sammeln können.

Diese sollten am besten in den prototypes-Ordner abgespeichert werden, wenn möglich in einen eigenen Ordner.

**Comment by Sagamir** [comment]
*hust* Nicht mehr viel Zeit bis zur Deadline *hust*

**Comment by D4rkTr4x** [comment]
Wie funktioniert das noch gleich mit dem pushen? Kann das einer von euch für besonders blöde erklären? Danke.

**Comment by Sagamir** [comment]
Ich benutz Github Desktop dafür: https://desktop.github.com/
und hier steht wie es funktioniert: https://help.github.com/desktop/guides/contributing/

**Comment by D4rkTr4x** [comment]
okay, danke. Ich werd`s dann mal so versuchen ;)

**Comment by MrHaython** [comment]
Lukas, sieht schon recht gut aus - also vom Design eine 1a. 

Ich denke aber, dass es zu sehr Richtung einfache Webseite geht. Aber mir gefällt deine Idee schon sehr gut. Ich überlege mir morgen oder so wie man das ganze gut präsentieren kann ;)

**Comment by Sagamir** [comment]
Ich bin ja gerade dabei das ganze umzusetzen.
Ich finde oben links ist es noch etwas leer.
Wie wäre es da mit einem Logo?

Idee: Ein "L", "E" und "D" die untereinander in sich verhakt sind.

**Comment by MrHaython** [comment]
Hast du schon was Handfestes? Weil ich arbeite gerade auch an meiner Idee. Ich pushe gleich mal ein Bild, sobald ich was zu zeigen habe.

**Comment by Sagamir** [comment]
Ne, wie du siehst hab ich es nur auf die Schnelle gezeichnet und nichts in Digitaler Form.

**Comment by MrHaython** [comment]
Habe jetzt ein noch sehr unfertiges Design gepusht, soll aber nur eine Vorstellungen davon sein, wie man es machen könnte. Da wir recht wenig Content haben können wir das ganze sehr auseinander ziehen. Am besten auch direkt mit Icons ausschmücken und dann nach Standard One-Page-Design.

**Comment by MrHaython** [comment]
Da Dirk schon so weit in der Umsetzung ist denke ich brauchen wir keine komplett neuen Ideen zu entwickeln, sondern gehen mit dem, was Dirk angelegt hat. 

Konzentrieren wir uns darauf das ganze zu Ende zu bringen :)
