### ISSUE TITLE
Inhaltsbeschaffung 

### ISSUE THREAD

**Issue by MrHaython** [MrHaython/english#4]
Jeder sollte sich schon mal im groben den Text für die Seite, also den Inhalt, der letztendlich drauf kommen soll überlegen. Dazu zählen Bilder und sonstige Informationen. Am besten in einer Datei in den Prototypes-Ordner schieben, damit wird sie dort sammeln und damit arbeiten können.

**Comment by Sagamir** [comment]
Schreibe mal bitte den genauen Arbeitsauftrag der an der Tafel stand hier rein. Danke.

**Comment by MrHaython** [comment]
Aufgabenstellung:
"Write a wishlist/letter to your 'perfect' employer and your 'perfect' company -> design an advert for it"

**Comment by Sagamir** [comment]
Ok, das hat mich etwas verwirrt.
Sollen wir eine Wunschliste/Brief an unseren 'perfekten' Arbeitgeber schreiben und eine Bewerbung schreiben oder eine Werbeanzeige/"Wir suchen DICH" für die Firma machen oder eine "Ich such ein Job"-Anzeige?

Wie habt ihr das verstanden?

**Comment by MrHaython** [comment]
Ich denke Sie meint damit, dass wir eine Anzeige gestalten sollen, in der wir so gesagt den perfekten Arbeitsplatz beschrieben wird und Arbeitgeber sich bewerben können.
So nach dem Motto: Arbeitnehmer sucht Arbeitgeber, der das und das und das.

**Comment by Sagamir** [comment]
*hust* Nicht mehr viel Zeit bis zur Deadline *hust*

**Comment by D4rkTr4x** [comment]
Stimmt, Designarbeiten laufen bei mir auf Hochtouren...

**Comment by Sagamir** [comment]
Dann stell doch schon mal was online, wenn du was hast.

**Comment by D4rkTr4x** [comment]
noch nichts fertiges, im laufe des abends sollte es aber noch etwas werden

**Comment by MrHaython** [comment]
Ich werde mich wohl morgen, spätestens am Donnerstag nochmal richtig daran setzten. Sorry, wenn es bei mir etwas aus dem Zeitplan fliegt.

**Comment by MrHaython** [comment]
Ich hab gerade einen einfachen Text gepusht. Würde euch bitten sich das ganze anzuschauen unter Berücksichtigung des Kommentares zum Commit. Ich habe auch schon eine Designidee, hab aber alles nur auf Skizzen und im Kopf. Handfestes folgt ...

**Comment by MrHaython** [comment]
Jungs!!! Ganz wichtig! Wir müssen das ganze möglichst bald  fertig machen. Ich würde euch bitten sich jetzt besonders stark auf den Inhalt zu konzentrieren. Daher müssen wir alle uns schonmal über den Inhalt klar sein, Design und Umsetzung sollte recht schnell gemacht sein. Daher: Inhalt, Inhalt, Inhalt!!!

**Comment by D4rkTr4x** [comment]
Setze ich morgen noch einmal ran, um den Content zu erweitern. Ich denke aber, dass wir da schon eine ganz gute Basis haben. Denkt ihr denn, dass noch viel mehr auf nen Onepager passt?

**Comment by MrHaython** [comment]
Ich glaube mit Lukas' Erweiterung haben wir inhaltstechnisch auf alle Fälle genug. Falls ihr noch was habt könnt ihr das gerne hinzufügen. Ansonsten schließe ich fürs erste dieses Issue
